dist: precise
sudo: false
language: php

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install

jobs:
  include:
  - stage: deploy
    php: 5.6
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then ./release/build_release_package.sh ; fi
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file: cloud-integration-magento-${TRAVIS_TAG}.tgz
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      secure: y40pECJxcziSDPLqL/xjAUYR2wcgEYK8lLAh+qGrwwnQd19PVqZzcht0LfPiFC0HHO+lULvzwBZe1iMLLt91h2IDKvtkXHrwPIOr5RJiciPifKnhA/QK28Xc2XEfrooL4IPsf+eTSyB3Y6EmSqnSOPiIhOXW8YogzgNvfUbFnsUKReX3z1F+vfvy2vZ4einL1E5Qkyclk89apvans+0bFvnJHrlfw+6rXsrGLhkjr2f2GopmAA6sHOZqBTvwCEKbtxYfWB3gZl9LMfdWjUJv1VhX3CsieQKPGdzIagZY3GLX3pFX8vk08/8k4ystmmHWetvceKQBfrdZ/NcT25lqtKPtL6Wus4gVcKqhmVXyqElGNirrLK0CeuZ2lGbgkt1h2YDUYhbs0lPu4hv2LfP6wj5Ct3fvfiYCBiGPO5Ql9hGNFUNJJjkmtiaolqbHZ1XbD5ODftMMGUsIZWKnXe97gizbofHEvjIxfcbG+npQZ3yunaMwOzQhfV/Gay4enR08Rq67k2g1A0kCdY/G6hb5kKP5gfvXlp75cqaVeW2p1zbx8nhTYlU84YAHtxm2bMWPXrn/Gesc3jZZzWjGV01YO7qnhn54s5DeSePQIWLNzymxghJ+vCbju0GAmznUJrjwjylRaRpm+yQbkS5RaFaA94hdTLT5PzqjC2H8uVuYAOU=
    on_success: change
    on_failure: always
